name: Main
"on":
  push:
    branches:
      - main
env:
  GODOT_VERSION: 4.5.1-stable
jobs:
  publish:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          username: ${{ github.actor }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            GODOT_VERSION=${{ env.GODOT_VERSION }}
          push: true
          tags: ghcr.io/aaronellington/godot:${{ env.GODOT_VERSION }}
